
biocypher:
    debug: false
    offline: true
    dbms: biopathnet

    # Ontology configuration
    head_ontology:
        url: {{ONTOLOGY_URL}}
        root_node: Biocypherroot

biopathnet:
    file_format: txt
    entity_types_file_stem: entity_types
    entity_names_file_stem: entity_names
    background_graph_file_stem: brg
    skg_file_stem: skg
    targeted_relation: "(Person, {{RELATION}}, Person)"
    include_properties: False
